version: '3.9'

services:

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - local
    volumes:
      - ./data:/data/db
    restart: always
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongosh 0.0.0.0:${MONGO_PORT}/ --quiet"
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 30s

networks:
  local:
    name: local
    driver: bridge
